README.md
src/CatLib.Core.Tests/CatLib/FacaedTests.cs
src/CatLib.Core.Tests/Properties/AssemblyInfo.cs
src/CatLib.Core.Tests/Support/Container/ContainerHelperTests.cs
src/CatLib.Core.Tests/Support/Container/ContainerPerformanceTests.cs
src/CatLib.Core/CatLib/App.cs
src/CatLib.Core/CatLib/Application.cs
src/CatLib.Core/CatLib/Facade.cs
src/CatLib.Core/Properties/AssemblyInfo.cs
src/CatLib.Core/Support/Container/Container.cs
src/CatLib.Core/Support/Container/ContainerExtend.cs
src/CatLib.Core/Support/Container/IContainer.cs

- `Facade` 拥有更好的性能。
- `App.Make` 拥有更好的性能。
- `App.Release` 可以获取一个返回值，表示是否成功的释放。

1.2.1 Version

---

src/CatLib.Core/Support/Stream/CombineStream.cs

resolved #70

---

CHANGELOG.md
src/CatLib.Core.Tests/Support/Util/StrTests.cs
src/CatLib.Core/Support/Util/Str.cs

| Q | A |
|----|----|
| Branch? |  v1.4  |
| Bug fix? | Yes(#202 ) |
| Tests pass? | N/A |
Fix Str.Repeat If the number of repetitions is 0, an abnormal result will be returned.
Now it will be returned `string.Empty`

Fix Str.Repeat If the number of repetitions is 0, an abnormal result will be returned.

---

src/CatLib.Core/Support/Container/Container.cs

| Q | A |
|----|----|
| Internal Changed? | Yes(#205 ) |
Define `Container.Build` as a virtual function.
It will be very useful when creating features like object pools.
The developer overrides this function to implement the response function.

Define Container.Build as a virtual function

---

src/CatLib.Core.Tests/Support/Container/ContainerHelperTests.cs

| Q | A |
|----|----|
| Removed | Yes |
The commit removes the IAwait interface, please use `IAsyncResult` instead.

Removed IAwait interface.

---

src/CatLib.Core/Support/Container/Container.cs
src/CatLib.Core/Support/Container/MethodContainer.cs

| Q | A |
|----|----|
This commit optimizes the constructor of MethodContainer, removing unnecessary arguments.

MethodContainer constructor optimization.

---

src/CatLib.Core.Tests/Support/Util/ArrTests.cs
src/CatLib.Core/Support/Util/Arr.cs

| Q | A |
|----|----|
| Removed | Yes |
This submission removes the Arr.Flash method. Because this API looks bad smell.

Removed Arr.Flash method.

---

src/CatLib.Core.Tests/Support/Container/ContainerTests.cs
src/CatLib.Core/Support/Container/Container.cs
src/CatLib.Core/Support/Container/VariantAttribute.cs

| Q | A |
|----|----|
The submission changes `IVariant` to an `VariantAttribute`.  Because empty interfaces are not recommended in the guide.

Change IVariant to VariantAttribute.

---

src/CatLib.Core/Support/Guard/Guard.cs

| Q | A |
|----|----|
This commit allows the `Guard` class to be extended by developers to extend the `Guard` by extension functions.

add Guard expandable supported.

---

src/CatLib.Core.Tests/CatLib/ApplicationTests.cs
src/CatLib.Core.Tests/Container/MethodContainerTests.cs
src/CatLib.Core/CatLib/App.cs
src/CatLib.Core/CatLib/Application.cs

| Q | A |
|----|----|
This commit adjusts the App.Handler to App.That and removes the App.HasHandler property. Because this property is no longer necessary

rename App.Handler to App.That

---

src/CatLib.Core.Tests/Support/Stream/CombineStreamTests.cs
src/CatLib.Core.Tests/Support/Stream/SegmentStreamTests.cs
src/CatLib.Core/Support/Extension/ExtendStream.cs
src/CatLib.Core/Support/Extension/ExtendString.cs
src/CatLib.Core/Support/Str.cs

| Q | A |
|----|----|
This commit removes the definition of `Str.Encoding` because we don't want to control global Encoding through a static object.

Removed Str.Encoding

---

src/CatLib.Core/Support/Stream/CombineStream.cs
src/CatLib.Core/Support/Stream/PipelineStream.cs

| Q | A |
|----|----|
This commit adjusts the inheritance relationship of Stream object

Inheritance relationship adjustment.

---

src/CatLib.Core/CatLib/Application.cs
src/CatLib.Core/CatLib/DebugLevel.cs
src/CatLib.Core/CatLib/Facade.cs
src/CatLib.Core/CatLib/ServiceProvider.cs
src/CatLib.Core/Container/BindData.cs
src/CatLib.Core/Container/Bindable.cs
src/CatLib.Core/Container/ExtendBindData.cs
src/CatLib.Core/Container/ExtendContainer.cs
src/CatLib.Core/Container/GivenData.cs
src/CatLib.Core/Container/IParams.cs
src/CatLib.Core/Container/MethodBind.cs
src/CatLib.Core/Container/MethodContainer.cs
src/CatLib.Core/Container/ParamsCollection.cs
src/CatLib.Core/EventDispatcher/IEventDispatcher.cs
src/CatLib.Core/Support/Arr.cs
src/CatLib.Core/Support/Helper.cs
src/CatLib.Core/Support/SortSet.cs
src/CatLib.Core/Support/Stream/PipelineStream.cs

| Q | A |
|----|----|
The commit optimizes the comments and removes some unnecessary comments

comment optimization.

---

src/CatLib.Core.Tests/Support/TestsGuard.cs
src/CatLib.Core/Container/BindData.cs
src/CatLib.Core/Container/Container.cs
src/CatLib.Core/Support/Guard.cs

| Q | A |
|----|----|
| New feature? | Yes |
| Removed | No|
This commit refactors the `Guard` class, adds messages when throwing exceptions, and internal exceptions, while allowing developers to customize exception factories to generate exceptions.

Refactors Guard classes.

---

src/CatLib.Core.Tests/CatLib/TestsApplication.cs
src/CatLib.Core.Tests/Container/TestsBindData.cs
src/CatLib.Core.Tests/Container/TestsContainer.cs
src/CatLib.Core.Tests/Container/TestsExtendContainer.cs
src/CatLib.Core.Tests/EventDispatcher/TestsEventDispatcher.cs
src/CatLib.Core.Tests/Framework/ExpectedExceptionAndMessageAttribute.cs
src/CatLib.Core.Tests/Framework/TestException.cs
src/CatLib.Core.Tests/Support/Stream/TestsRingBuffer.cs
src/CatLib.Core.Tests/Support/TestsGuard.cs
src/CatLib.Core/CatLib/Application.cs
src/CatLib.Core/CatLib/Facade.cs
src/CatLib.Core/Container/BindData.cs
src/CatLib.Core/Container/Bindable.cs
src/CatLib.Core/Container/Container.cs
src/CatLib.Core/Container/ExtendContainer.cs
src/CatLib.Core/Container/MethodContainer.cs
src/CatLib.Core/Container/UnresolvableException.cs
src/CatLib.Core/EventDispatcher/EventDispatcher.cs
src/CatLib.Core/Exception/AssertException.cs
src/CatLib.Core/Exception/LogicException.cs
src/CatLib.Core/Exception/RuntimeException.cs
src/CatLib.Core/Support/Arr.cs
src/CatLib.Core/Support/Extension/ExtendStream.cs
src/CatLib.Core/Support/Guard.cs
src/CatLib.Core/Support/Stream/CombineStream.cs
src/CatLib.Core/Support/Stream/RingBufferStream.cs

| Q | A |
|----|----|
| Tests pass? | No |
The commit moved the Exception namespace, Moved from `CatLib.Support` to `CatLib.Exception`

Move the exception namespace.

---

src/CatLib.Core.Tests/CatLib/TestsFacade.cs
src/CatLib.Core/CatLib/App.cs
src/CatLib.Core/CatLib/Facade.cs

| Q | A |
|----|----|
Renamed Facade.Instance to Facade.That. Also corrected some internal variable naming.

Facade.Instance rename to Facade.That

---

.travis.yml
src/CatLib.Core.Tests/CatLib/TestsApplication.cs
src/CatLib.Core.Tests/Container/TestsBindData.cs
src/CatLib.Core.Tests/Container/TestsExtendContainer.cs
src/CatLib.Core.Tests/EventDispatcher/TestsEventDispatcher.cs
src/CatLib.Core.Tests/Framework/TestException.cs
src/CatLib.Core/CatLib/Facade.cs
src/CatLib.Core/Container/ExtendContainer.cs
src/CatLib.Core/Support/Arr.cs
src/CatLib.Core/Support/Extension/ExtendInt.cs
src/CatLib.Core/Support/Extension/ExtendStream.cs
src/CatLib.Core/Support/Helper.cs
src/CatLib.Core/Support/SortSet.cs
src/CatLib.Core/Support/Str.cs

| Q | A |
|----|----|
| Removed | Yes |
The commit removed the obsolete flag method，and clean the code.

Removed obsolete and clean code.

---

src/CatLib.Core.Tests/CatLib/TestsApplication.cs
src/CatLib.Core.Tests/EventDispatcher/TestsEventDispatcher.cs
src/CatLib.Core.Tests/Fixture/TestEventArgs.cs
src/CatLib.Core/CatLib/Application.cs
src/CatLib.Core/CatLib/Events/AfterBootEventArgs.cs
src/CatLib.Core/CatLib/Events/AfterInitEventArgs.cs
src/CatLib.Core/CatLib/Events/AfterTerminateEventArgs.cs
src/CatLib.Core/CatLib/Events/ApplicationEventArgs.cs
src/CatLib.Core/CatLib/Events/ApplicationEvents.cs
src/CatLib.Core/CatLib/Events/BeforeBootEventArgs.cs
src/CatLib.Core/CatLib/Events/BeforeInitEventArgs.cs
src/CatLib.Core/CatLib/Events/BeforeTerminateEventArgs.cs
src/CatLib.Core/CatLib/Events/BootingEventArgs.cs
src/CatLib.Core/CatLib/Events/InitProviderEventArgs.cs
src/CatLib.Core/CatLib/Events/RegisterProviderEventArgs.cs
src/CatLib.Core/CatLib/Events/StartCompletedEventArgs.cs
src/CatLib.Core/EventDispatcher/EventDispatcher.cs
src/CatLib.Core/EventDispatcher/IEventDispatcher.cs

| Q | A |
|----|----|
| Internal Changed? | Yes(#177 ) |
Submit redesigned interface to avoid using generics

refactor event system.

---

src/CatLib.Core.Tests/Support/TestsArr.cs
src/CatLib.Core/Support/Arr.cs

| Q | A |
|----|----|
This submission optimizes the variable naming and guarding of Arr.cs

Arr.cs optimization variable naming and guarding

---

src/CatLib.Core.Tests/Support/TestsStr.cs
src/CatLib.Core/Support/Str.cs

| Q | A |
|----|----|
This submission optimizes the variable naming and guarding of Str.cs

Str.cs optimization variable naming and guarding

---

src/CatLib.Core.Tests/CatLib/TestsFacade.cs
src/CatLib.Core/CatLib/Application.cs

| Q | A |
|----|----|
this commit removed `global` params in application constructor.  use `Application.New()` instead.

Removed global params in application constructor.

---

src/CatLib.Core/Container/BindData.cs
src/CatLib.Core/Container/Bindable.cs
src/CatLib.Core/Container/Container.cs
src/CatLib.Core/Container/MethodContainer.cs

| Q | A |
|----|----|
Containers are no longer thread-safe by default. Because in most cases we don't need thread safety, and existing thread safety can make the code messy.

Container is not thread-safe by default.

---

src/CatLib.Core.Tests/Container/TestsContainer.cs
src/CatLib.Core.Tests/Fixture/Fubar.cs
src/CatLib.Core.Tests/Fixture/ProtectedProperty.cs
src/CatLib.Core/Container/Container.cs
src/analysis.ruleset

When the Inject tag is incorrectly used or the constructor is incorrectly declared, a clear prompt message will be given
```txt
Create CatLib.Tests.Fixture.Quux faild, service name is quux.
This issue may be caused because your constructor is not public.
While building stack [quux].
InnerException message stack: [System.MissingMethodException: No parameterless constructor defined for type 'CatLib.Tests.Fixture.Quux'.
at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
at System.Activator.CreateInstance(Type …
```

Enhanced debug information for create instance and inject property.

---

src/CatLib.Core.Tests/CatLib/TestsApplication.cs
src/CatLib.Core.Tests/Container/TestsContainer.cs
src/CatLib.Core.Tests/Framework/ExpectedExceptionAndMessageAttribute.cs

The commit allows wildcarding with asterisk wildcards in exception assertion attributes.
Fixed a buggy design, exception assertions should check the exception itself and should not detect internal exceptions.
resolved #285

Enhance ExpectedExceptionAndMessageAttribute to support asterisk wildcard.
